# Generated by Django 4.1.2 on 2022-12-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(upload_to="company_logo")),
                ("post", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=30)),
                ("job_type", models.CharField(max_length=10)),
                ("date_of_release", models.DateField()),
                ("salary", models.IntegerField()),
                ("job_desc", models.TextField()),
                ("responsibility_desc", models.TextField()),
                ("qualification_desc", models.TextField()),
            ],
        ),
    ]
