# Generated by Django 4.0.8 on 2023-03-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_email_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
