# Generated by Django 4.0.8 on 2023-03-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_application_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_post',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
