# Generated by Django 4.0.8 on 2023-03-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_application_job_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job_post',
            field=models.TextField(),
        ),
    ]
